package com.ashurex.springcustomacl.security.config;

import java.util.UUID;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * @author Mustafa Ashurex
 */
@ConfigurationProperties(prefix = "ashurex.security.jwt")
public class SecurityJwtConfigProperties {
	/**
	 * Signing key for creating/verifying JWT tokens. A random key is generated by default.
	 */
	private String signingKey = UUID.randomUUID().toString();

	public String getSigningKey() {
		return signingKey;
	}

	public void setSigningKey(String signingKey) {
		this.signingKey = signingKey;
	}
}
